title: Maria Serova 
description: >
  <strong>ML-Bio Scientist</strong><br>
  <a href="mailto:serovmari@gmail.com">serovmari@gmail.com</a><br>
  <a href="https://github.com/mariaserov">GitHub</a><br>
  <a href="https://www.linkedin.com/in/maria-serova/">LinkedIn</a> 
  <br> <br>
  <strong>Executive Summary:</strong> A research scientist and innovator with a unique blend 
  of expertise at the intersection of AI, biology, and entrepreneurship. Combining academic rigour 
  with industry efficiency to unlock ML to solve biology.
  <br> <br>
  ðŸŽ“: <br>
  <strong>Oxford University</strong> (Biochemistry)
  <strong>Imperial College London</strong> (Machine Learning)
  <br> <br>


#theme: minimal     
remote_theme: pages-themes/minimal@v0.2.0
logo: avatar.png

